
'use client';

import type { Ingredient, CategoryDef, Recipe, HealthConditionCategory } from '@/lib/types';

export const initialCategories: CategoryDef[] = [
  { id: 'c1', name: 'Fruits et Légumes' },
  { id: 'c2', name: 'Viandes et Poissons' },
  { id: 'c3', name: 'Produits Laitiers & Oeufs' },
  { id: 'c4', name: 'Boulangerie & Pâtisserie' },
  { id: 'c5', name: 'Épicerie Salée' },
  { id: 'c6', name: 'Épicerie Sucrée' },
  { id: 'c7', name: 'Boissons' },
  { id: 'c8', name: 'Surgelés' },
];

export const initialHealthConditions: HealthConditionCategory[] = [
  {
    id: 'hc_cat_1',
    name: "Maladies Chroniques",
    conditions: [
      { id: 'hc_1_1', name: "Cholestérol élevé" },
      { id: 'hc_1_2', name: "Hypertension" },
      { id: 'hc_1_3', name: "Diabète type 1" },
      { id: 'hc_1_4', name: "Diabète type 2" },
      { id: 'hc_1_5', name: "Diabète gestationnel" },
    ]
  },
  {
    id: 'hc_cat_2',
    name: "Carences & Sensibilités",
    conditions: [
      { id: 'hc_2_1', name: "Carence en Fer" },
      { id: 'hc_2_2', name: "Carence en Vitamine D" },
      { id: 'hc_2_3', name: "Intolérance au Lactose" },
      { id: 'hc_2_4', name: "Maladie Cœliaque (sans gluten)" },
    ]
  },
  {
    id: 'hc_cat_3',
    name: "Régimes & Objectifs",
    conditions: [
      { id: 'hc_3_1', name: "Végétarien" },
      { id: 'hc_3_2', name: "Végétalien" },
      { id: 'hc_3_3', name: "Perte de poids" },
      { id: 'hc_3_4', name: "Prise de masse musculaire" },
    ]
  }
];

export const predefinedIngredients: Ingredient[] = [
  // Fruits et Légumes
  { id: 'f1', name: 'Pommes', category: 'Fruits et Légumes', price: 2.5, unit: 'kg' },
  { id: 'f3', name: 'Tomates', category: 'Fruits et Légumes', price: 4.0, unit: 'kg' },
  { id: 'e3', name: 'Oignon', category: 'Fruits et Légumes', price: 2, unit: 'kg' },
  { id: 'f4', name: 'Ail', category: 'Fruits et Légumes', price: 8.0, unit: 'kg' },
  { id: 'f5', name: 'Carottes', category: 'Fruits et Légumes', price: 1.5, unit: 'kg' },
  { id: 'f6', name: 'Poivron', category: 'Fruits et Légumes', price: 5.0, unit: 'kg' },
  { id: 'f7', name: 'Laitue', category: 'Fruits et Légumes', price: 1.2, unit: 'pièce' },
  { id: 'f8', name: 'Concombre', category: 'Fruits et Légumes', price: 2.0, unit: 'kg' },
  { id: 'f9', name: 'Courgette', category: 'Fruits et Légumes', price: 3.0, unit: 'kg' },
  { id: 'f10', name: 'Citron', category: 'Fruits et Légumes', price: 0.8, unit: 'pièce' },
  { id: 'f11', name: 'Basilic frais', category: 'Fruits et Légumes', price: 2.5, unit: 'botte' },
  { id: 'f12', name: 'Navet', category: 'Fruits et Légumes', price: 1.8, unit: 'kg' },
  { id: 'f13', name: 'Aubergine', category: 'Fruits et Légumes', price: 4.5, unit: 'kg' },
  { id: 'f14', name: 'Pommes de terre', category: 'Fruits et Légumes', price: 2.2, unit: 'kg' },
  { id: 'f15', name: 'Champignons de Paris', category: 'Fruits et Légumes', price: 12.0, unit: 'kg' },
  { id: 'f16', name: 'Épinards frais', category: 'Fruits et Légumes', price: 6.0, unit: 'kg' },
  { id: 'f17', name: 'Gingembre frais', category: 'Fruits et Légumes', price: 15.0, unit: 'kg' },
  { id: 'f18', name: 'Coriandre fraîche', category: 'Fruits et Légumes', price: 2.0, unit: 'botte' },


  // Viandes et Poissons
  { id: 'v1', name: 'Filet de Poulet', category: 'Viandes et Poissons', price: 12.0, unit: 'kg' },
  { id: 'v2', name: 'Bœuf haché', category: 'Viandes et Poissons', price: 25.0, unit: 'kg' },
  { id: 'v3', name: 'Filet de saumon', category: 'Viandes et Poissons', price: 40.0, unit: 'kg' },
  { id: 'v4', name: 'Thon en conserve', category: 'Viandes et Poissons', price: 3.5, unit: 'boîte' },
  { id: 'v5', name: 'Gigot d\'agneau', category: 'Viandes et Poissons', price: 35.0, unit: 'kg' },
  { id: 'v6', name: 'Crevettes', category: 'Viandes et Poissons', price: 30.0, unit: 'kg' },
  { id: 'v7', name: 'Lardons fumés', category: 'Viandes et Poissons', price: 28.0, unit: 'kg' },


  // Produits Laitiers & Oeufs
  { id: 'p1', name: 'Lait Entier', category: 'Produits Laitiers & Oeufs', price: 1.8, unit: 'L' },
  { id: 'p2', name: 'Oeufs', category: 'Produits Laitiers & Oeufs', price: 4.0, unit: 'douzaine' },
  { id: 'p3', name: 'Yaourt nature', category: 'Produits Laitiers & Oeufs', price: 0.8, unit: 'pièce' },
  { id: 'p4', name: 'Fromage Gruyère', category: 'Produits Laitiers & Oeufs', price: 30.0, unit: 'kg' },
  { id: 'p5', name: 'Mozzarella', category: 'Produits Laitiers & Oeufs', price: 25.0, unit: 'kg' },
  { id: 'p6', name: 'Parmesan', category: 'Produits Laitiers & Oeufs', price: 45.0, unit: 'kg' },
  { id: 'p7', name: 'Beurre', category: 'Produits Laitiers & Oeufs', price: 5.0, unit: '250g' },
  { id: 'p8', name: 'Crème fraîche', category: 'Produits Laitiers & Oeufs', price: 2.5, unit: 'pot' },
  { id: 'p9', name: 'Feta', category: 'Produits Laitiers & Oeufs', price: 15.0, unit: '200g' },

  // Boulangerie & Pâtisserie
  { id: 'b1', name: 'Baguette', category: 'Boulangerie & Pâtisserie', price: 0.4, unit: 'pièce' },
  { id: 'b2', name: 'Pain de mie', category: 'Boulangerie & Pâtisserie', price: 2.5, unit: 'paquet' },
  { id: 'b3', name: 'Pâte à pizza', category: 'Boulangerie & Pâtisserie', price: 3.0, unit: 'pièce' },
  { id: 'b4', name: 'Croûtons', category: 'Boulangerie & Pâtisserie', price: 2.0, unit: 'paquet' },
  { id: 'b5', name: 'Farine', category: 'Boulangerie & Pâtisserie', price: 2.0, unit: 'kg' },
  { id: 'b6', name: 'Sucre', category: 'Boulangerie & Pâtisserie', price: 1.8, unit: 'kg' },
  { id: 'b7', name: 'Levure de boulanger', category: 'Boulangerie & Pâtisserie', price: 1.0, unit: 'sachet' },


  // Épicerie Salée
  { id: 'e1', name: 'Pâtes Penne', category: 'Épicerie Salée', price: 1.5, unit: 'paquet' },
  { id: 'e2', name: 'Huile d\'olive', category: 'Épicerie Salée', price: 15, unit: 'L' },
  { id: 'e4', name: 'Riz basmati', category: 'Épicerie Salée', price: 5.0, unit: 'kg' },
  { id: 'e7', name: 'Sel', category: 'Épicerie Salée', price: 1.0, unit: 'paquet' },
  { id: 'e8', name: 'Poivre noir', category: 'Épicerie Salée', price: 4.0, unit: 'pot' },
  { id: 'e9', name: 'Haricots rouges en conserve', category: 'Épicerie Salée', price: 2.5, unit: 'boîte' },
  { id: 'e10', name: 'Semoule de couscous', category: 'Épicerie Salée', price: 3.5, unit: 'kg' },
  { id: 'e11', name: 'Cumin en poudre', category: 'Épicerie Salée', price: 3.0, unit: 'pot' },
  { id: 'e12', name: 'Piment en poudre (Paprika)', category: 'Épicerie Salée', price: 2.8, unit: 'pot' },
  { id: 'e13', name: 'Vinaigre de vin', category: 'Épicerie Salée', price: 4.0, unit: 'L' },
  { id: 'e14', name: 'Harissa en conserve', category: 'Épicerie Salée', price: 2.2, unit: 'boîte' },
  { id: 'e15', name: 'Pois chiches en conserve', category: 'Épicerie Salée', price: 2.0, unit: 'boîte' },
  { id: 'e16', name: 'Concentré de tomate', category: 'Épicerie Salée', price: 1.8, unit: 'boîte' },
  { id: 'e17', name: 'Moutarde de Dijon', category: 'Épicerie Salée', price: 3.5, unit: 'pot' },
  { id: 'e18', name: 'Lentilles corail', category: 'Épicerie Salée', price: 6.0, unit: 'kg' },
  { id: 'e19', name: 'Lait de coco', category: 'Épicerie Salée', price: 4.5, unit: 'boîte' },
  { id: 'e20', name: 'Sauce soja', category: 'Épicerie Salée', price: 5.0, unit: 'bouteille' },
  { id: 'e21', name: 'Bouillon de volaille', category: 'Épicerie Salée', price: 2.0, unit: 'cube' },
  { id: 'e22', name: 'Curcuma', category: 'Épicerie Salée', price: 3.0, unit: 'pot' },

  // Épicerie Sucrée
  { id: 'es1', name: 'Chocolat noir pâtissier', category: 'Épicerie Sucrée', price: 5.0, unit: 'tablette' },
  { id: 'es2', name: 'Miel', category: 'Épicerie Sucrée', price: 12.0, unit: 'pot' },
  { id: 'es3', name: 'Confiture de fraises', category: 'Épicerie Sucrée', price: 4.0, unit: 'pot' },
  { id: 'es4', name: 'Cacao en poudre', category: 'Épicerie Sucrée', price: 6.0, unit: 'boîte' },

  // Boissons
  { id: 'bo1', name: 'Eau minérale', category: 'Boissons', price: 0.8, unit: 'L' },
  { id: 'bo2', name: 'Café moulu', category: 'Boissons', price: 7.0, unit: 'paquet' },
  { id: 'bo3', name: 'Thé vert', category: 'Boissons', price: 3.0, unit: 'boîte' },
];

export const streetFoodOptions: string[] = [
  'Quésadilla',
  'Burrito',
  'Fricassé',
  'Tacos Mexicain',
  'Tacos',
  'Ma9loub',
  'Pizza',
  'Chapati',
  'Baguette farcie',
  'Lablebi royal',
  'Poulet prêt à porter',
  'Panuzzo',
  'Ciabatta',
];

export const discoverableRecipes: Recipe[] = [
  {
    id: 'r1',
    title: 'Spaghetti Carbonara',
    description: 'Un plat de pâtes italien classique, crémeux et savoureux, prêt en un rien de temps.',
    country: 'Italie',
    calories: 650,
    portions: 4,
    preparationTime: 20,
    isEconomical: false,
    ingredients: [
      { name: 'Spaghetti', quantity: 400, unit: 'g' },
      { name: 'Pancetta ou guanciale', quantity: 150, unit: 'g' },
      { name: 'Jaunes d\'œufs', quantity: 4, unit: 'pièce' },
      { name: 'Pecorino Romano râpé', quantity: 50, unit: 'g' },
      { name: 'Poivre noir', quantity: 1, unit: 'cuillère à café' },
    ],
    preparation: `1. Faites cuire les pâtes dans une grande casserole d'eau bouillante salée.\n2. Pendant ce temps, faites dorer la pancetta coupée en lardons dans une poêle.\n3. Dans un bol, mélangez les jaunes d'œufs, le fromage pecorino et beaucoup de poivre noir.\n4. Égouttez les pâtes en réservant un peu d'eau de cuisson. Versez les pâtes dans la poêle avec la pancetta.\n5. Hors du feu, ajoutez le mélange d'œufs et de fromage. Mélangez rapidement. Si c'est trop sec, ajoutez un peu d'eau de cuisson.\n6. Servez immédiatement avec plus de fromage râpé.`,
  },
  {
    id: 'r2',
    title: 'Tajine de poulet aux citrons confits',
    description: 'Un plat marocain parfumé et fondant, sucré-salé, qui fait voyager les papilles.',
    country: 'Maroc',
    calories: 550,
    portions: 4,
    preparationTime: 60,
    isEconomical: false,
    ingredients: [
      { name: 'Cuisses de poulet', quantity: 4, unit: 'pièce' },
      { name: 'Oignons', quantity: 2, unit: 'pièce' },
      { name: 'Citrons confits', quantity: 2, unit: 'pièce' },
      { name: 'Olives vertes', quantity: 100, unit: 'g' },
      { name: 'Gingembre frais râpé', quantity: 1, unit: 'cuillère à soupe' },
      { name: 'Curcuma', quantity: 1, unit: 'cuillère à café' },
      { name: 'Coriandre fraîche', quantity: 1, unit: 'botte' },
      { name: 'Huile d\'olive', quantity: 2, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Faites dorer les morceaux de poulet dans un tajine ou une cocotte avec l'huile d'olive.\n2. Retirez le poulet et faites revenir les oignons émincés jusqu'à ce qu'ils soient tendres.\n3. Remettez le poulet, ajoutez les épices (gingembre, curcuma), salez, poivrez. Couvrez d'eau à mi-hauteur.\n4. Laissez mijoter à couvert pendant 30 minutes.\n5. Ajoutez les citrons confits coupés en quartiers et les olives. Poursuivez la cuisson 15 minutes.\n6. Parsemez de coriandre fraîche ciselée avant de servir.`,
  },
  {
    id: 'r3',
    title: 'Ramen Tonkotsu',
    description: 'Une soupe de nouilles japonaise riche et réconfortante avec un bouillon de porc crémeux.',
    country: 'Japon',
    calories: 800,
    portions: 2,
    preparationTime: 120,
    isEconomical: false,
    ingredients: [
      { name: 'Nouilles ramen', quantity: 400, unit: 'g' },
      { name: 'Tranches de porc Chashu', quantity: 8, unit: 'pièce' },
      { name: 'Oeufs mollets marinés (Ajitama)', quantity: 2, unit: 'pièce' },
      { name: 'Pousse de bambou (Menma)', quantity: 50, unit: 'g' },
      { name: 'Ciboule émincée', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Bouillon Tonkotsu (porc)', quantity: 1, unit: 'L' },
    ],
    preparation: `1. Préparez tous les toppings : coupez les œufs en deux, réchauffez le porc Chashu.\n2. Portez le bouillon Tonkotsu à ébullition.\n3. Faites cuire les nouilles ramen selon les instructions du paquet. Égouttez-les bien.\n4. Répartissez les nouilles dans des grands bols.\n5. Versez délicatement le bouillon chaud sur les nouilles.\n6. Disposez harmonieusement les tranches de porc, l'œuf, les pousses de bambou et la ciboule sur le dessus.\n7. Servez très chaud et dégustez en aspirant bruyamment les nouilles !`,
  },
  {
    id: 'r4',
    title: 'Tacos al Pastor',
    description: 'Le goût de Mexico dans une tortilla, avec du porc mariné, de l\'ananas et une salsa fraîche.',
    country: 'Mexique',
    calories: 450,
    portions: 4,
    preparationTime: 30,
    isEconomical: false,
    ingredients: [
      { name: 'Filet de porc', quantity: 500, unit: 'g' },
      { name: 'Pâte d\'achiote', quantity: 50, unit: 'g' },
      { name: 'Jus d\'ananas', quantity: 100, unit: 'ml' },
      { name: 'Ananas frais en dés', quantity: 1, unit: 'tasse' },
      { name: 'Oignon rouge émincé', quantity: 1, unit: 'pièce' },
      { name: 'Coriandre fraîche hachée', quantity: 1, unit: 'botte' },
      { name: 'Tortillas de maïs', quantity: 12, unit: 'pièce' },
    ],
    preparation: `1. Coupez le porc en fines tranches. Mélangez la pâte d'achiote avec le jus d'ananas et marinez la viande pendant au moins 2 heures.\n2. Faites cuire le porc dans une poêle chaude jusqu'à ce qu'il soit bien cuit et légèrement caramélisé.\n3. Dans la même poêle, faites griller les dés d'ananas.\n4. Réchauffez les tortillas de maïs.\n5. Garnissez chaque tortilla avec le porc, quelques dés d'ananas grillés, de l'oignon rouge et de la coriandre fraîche.\n6. Servez avec des quartiers de lime et votre salsa préférée.`,
  },
  {
    id: 'r5',
    title: 'Bœuf Bourguignon',
    description: 'Un ragoût de bœuf français emblématique, mijoté lentement dans du vin rouge.',
    country: 'France',
    calories: 700,
    portions: 6,
    preparationTime: 200,
    isEconomical: false,
    ingredients: [
      { name: 'Bœuf à braiser (paleron, gîte)', quantity: 1, unit: 'kg' },
      { name: 'Vin rouge de Bourgogne', quantity: 750, unit: 'ml' },
      { name: 'Lardons fumés', quantity: 200, unit: 'g' },
      { name: 'Champignons de Paris', quantity: 250, unit: 'g' },
      { name: 'Carottes', quantity: 2, unit: 'pièce' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Bouquet garni', quantity: 1, unit: 'pièce' },
    ],
    preparation: `1. Coupez le bœuf en morceaux. Faites-le mariner dans le vin rouge avec les carottes et l'oignon coupés, et le bouquet garni, pendant 12h.\n2. Égouttez la viande. Faites-la dorer dans une cocotte avec un peu d'huile.\n3. Ajoutez les légumes de la marinade, faites-les revenir. Saupoudrez de farine, mélangez bien.\n4. Versez la marinade filtrée. Complétez avec du bouillon si nécessaire pour couvrir. Laissez mijoter à feu très doux pendant 3 heures.\n5. Faites revenir les lardons et les champignons à part.\n6. Ajoutez-les à la cocotte 30 minutes avant la fin de la cuisson. Servez chaud avec des pommes de terre vapeur.`
  },
  {
    id: 'r6',
    title: 'Moussaka',
    description: 'Un gratin grec généreux avec des aubergines, de la viande hachée et une sauce béchamel onctueuse.',
    country: 'Grèce',
    calories: 750,
    portions: 6,
    preparationTime: 90,
    isEconomical: false,
    ingredients: [
      { name: 'Aubergine', quantity: 3, unit: 'pièce' },
      { name: 'Bœuf haché', quantity: 500, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Tomates pelées', quantity: 400, unit: 'g' },
      { name: 'Lait', quantity: 500, unit: 'ml' },
      { name: 'Farine', quantity: 50, unit: 'g' },
      { name: 'Beurre', quantity: 50, unit: 'g' },
      { name: 'Fromage râpé', quantity: 100, unit: 'g' },
    ],
    preparation: `1. Coupez les aubergines en tranches, salez-les et laissez-les dégorger. Rincez-les et faites-les frire ou griller.\n2. Faites revenir l'oignon émincé, ajoutez la viande hachée et faites-la dorer. Ajoutez les tomates, salez, poivrez et laissez mijoter.\n3. Préparez une béchamel avec le beurre, la farine et le lait. Ajoutez une partie du fromage.\n4. Dans un plat à gratin, alternez couches d'aubergines et de viande. Terminez par la béchamel et le reste du fromage.\n5. Enfournez à 180°C pendant 45 minutes.`
  },
  {
    id: 'r7',
    title: 'Curry Vert Thaï au Poulet',
    description: 'Un curry thaïlandais crémeux, épicé et plein de saveurs, servi avec du riz jasmin.',
    country: 'Thaïlande',
    calories: 600,
    portions: 4,
    preparationTime: 30,
    isEconomical: false,
    ingredients: [
      { name: 'Filet de poulet', quantity: 400, unit: 'g' },
      { name: 'Pâte de curry vert', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Lait de coco', quantity: 400, unit: 'ml' },
      { name: 'Pois gourmands', quantity: 100, unit: 'g' },
      { name: 'Poivron', quantity: 1, unit: 'pièce' },
      { name: 'Feuilles de basilic thaï', quantity: 1, unit: 'botte' },
      { name: 'Sauce poisson (nuoc-mâm)', quantity: 1, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Coupez le poulet en morceaux et le poivron en lanières.\n2. Dans un wok, faites chauffer un peu d'huile, puis ajoutez la pâte de curry vert et faites-la revenir pendant 1 minute.\n3. Ajoutez le poulet et faites-le dorer. Versez le lait de coco et portez à frémissement.\n4. Laissez mijoter 10 minutes. Ajoutez les pois gourmands et le poivron. Poursuivez la cuisson 5 minutes.\n5. Incorporez la sauce poisson et les feuilles de basilic thaï juste avant de servir avec du riz.`
  },
  {
    id: 'r8',
    title: 'Paella Valenciana',
    description: 'Le plat espagnol emblématique, un riz safrané garni de poulet, lapin et légumes verts.',
    country: 'Espagne',
    calories: 850,
    portions: 4,
    preparationTime: 60,
    isEconomical: false,
    ingredients: [
      { name: 'Riz Bomba', quantity: 400, unit: 'g' },
      { name: 'Poulet en morceaux', quantity: 500, unit: 'g' },
      { name: 'Lapin en morceaux', quantity: 250, unit: 'g' },
      { name: 'Haricots verts plats', quantity: 150, unit: 'g' },
      { name: 'Gros haricots blancs (garrofó)', quantity: 100, unit: 'g' },
      { name: 'Tomate mûre râpée', quantity: 1, unit: 'pièce' },
      { name: 'Safran', quantity: 1, unit: 'pincée' },
      { name: 'Bouillon de poulet', quantity: 1.2, unit: 'L' },
    ],
    preparation: `1. Dans une poêle à paella, faites dorer les viandes dans l'huile d'olive. Poussez-les sur les côtés.\n2. Au centre, faites revenir les haricots verts, puis ajoutez la tomate râpée. Mélangez tout.\n3. Versez le riz et nacrez-le pendant une minute. Ajoutez le safran.\n4. Versez le bouillon de poulet chaud, salez et ajoutez les haricots blancs. Répartissez bien les ingrédients.\n5. Laissez cuire à feu vif pendant 10 minutes, puis à feu doux pendant 8-10 minutes sans jamais remuer. Laissez reposer 5 minutes avant de servir.`
  },
  {
    id: 'r9',
    title: 'Poulet au Beurre (Butter Chicken)',
    description: 'Un plat indien crémeux et légèrement épicé, avec des morceaux de poulet marinés dans une sauce tomate riche.',
    country: 'Inde',
    calories: 680,
    portions: 4,
    preparationTime: 45,
    isEconomical: false,
    ingredients: [
      { name: 'Filet de poulet', quantity: 500, unit: 'g' },
      { name: 'Yaourt nature', quantity: 150, unit: 'g' },
      { name: 'Garam masala', quantity: 2, unit: 'cuillère à café' },
      { name: 'Purée de tomates', quantity: 400, unit: 'g' },
      { name: 'Crème liquide entière', quantity: 100, unit: 'ml' },
      { name: 'Beurre', quantity: 50, unit: 'g' },
      { name: 'Ail et gingembre', quantity: 1, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Coupez le poulet en cubes. Marinez-le pendant au moins 1 heure dans le yaourt avec du garam masala, de l'ail et du gingembre.\n2. Faites griller le poulet mariné au four ou à la poêle jusqu'à ce qu'il soit cuit.\n3. Dans une casserole, faites fondre le beurre. Ajoutez la purée de tomates, le reste du garam masala, salez et laissez mijoter 10 minutes.\n4. Ajoutez la crème liquide et mélangez bien. Incorporez les morceaux de poulet grillés.\n5. Laissez réchauffer l'ensemble quelques minutes. Servez chaud avec du riz basmati ou du pain naan.`
  },
  {
    id: 'r10',
    title: 'Pad Thaï',
    description: 'Le plat de nouilles sautées le plus célèbre de Thaïlande, un mélange parfait de sucré, salé et acide.',
    country: 'Thaïlande',
    calories: 700,
    portions: 2,
    preparationTime: 30,
    isEconomical: true,
    ingredients: [
      { name: 'Nouilles de riz plates', quantity: 200, unit: 'g' },
      { name: 'Crevettes ou poulet', quantity: 200, unit: 'g' },
      { name: 'Tofu ferme', quantity: 100, unit: 'g' },
      { name: 'Pousses de soja', quantity: 1, unit: 'tasse' },
      { name: 'Cacahuètes grillées', quantity: 4, unit: 'cuillère à soupe' },
      { name: 'Sauce de poisson', quantity: 3, unit: 'cuillère à soupe' },
      { name: 'Pâte de tamarin', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Sucre de palme', quantity: 2, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Faites tremper les nouilles de riz dans l'eau tiède. Préparez la sauce en mélangeant sauce de poisson, pâte de tamarin et sucre.\n2. Dans un wok, faites sauter le tofu, puis les crevettes ou le poulet. Ajoutez les nouilles égouttées et la sauce.\n3. Remuez constamment jusqu'à ce que les nouilles soient tendres. Poussez sur un côté et cassez un œuf sur l'autre côté. Brouillez-le, puis mélangez tout.\n4. Ajoutez les pousses de soja et la moitié des cacahuètes. Servez immédiatement, garni du reste de cacahuètes, de ciboulette et d'un quartier de lime.`
  },
  {
    id: 'r11',
    title: 'Pho Bo (Soupe Vietnamienne)',
    description: 'Une soupe de nouilles vietnamienne parfumée et réconfortante avec un bouillon de bœuf riche et des herbes fraîches.',
    country: 'Vietnam',
    calories: 500,
    portions: 4,
    preparationTime: 45,
    isEconomical: false,
    ingredients: [
      { name: 'Bouillon de bœuf', quantity: 1.5, unit: 'L' },
      { name: 'Bavette de bœuf', quantity: 200, unit: 'g' },
      { name: 'Nouilles de riz', quantity: 300, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Gingembre', quantity: 5, unit: 'cm' },
      { name: 'Anis étoilé', quantity: 2, unit: 'pièce' },
      { name: 'Bâton de cannelle', quantity: 1, unit: 'pièce' },
      { name: 'Herbes fraîches (menthe, coriandre, basilic thaï)', quantity: 1, unit: 'bouquet' },
    ],
    preparation: `1. Faites griller l'oignon et le gingembre. Mettez-les dans le bouillon avec l'anis et la cannelle. Laissez infuser 30 min.\n2. Coupez le bœuf en tranches très fines. Faites cuire les nouilles de riz.\n3. Répartissez les nouilles dans des bols. Disposez les tranches de bœuf cru par-dessus.\n4. Versez le bouillon très chaud sur le bœuf, ce qui le cuira instantanément.\n5. Garnissez généreusement d'herbes fraîches, de pousses de soja et de piment si désiré.`
  },
  {
    id: 'r12',
    title: 'Classic Cheeseburger',
    description: 'L\'icône américaine. Un steak juteux, du fromage fondant, dans un pain brioché moelleux.',
    country: 'USA',
    calories: 750,
    portions: 4,
    preparationTime: 20,
    isEconomical: false,
    ingredients: [
      { name: 'Bœuf haché (20% MG)', quantity: 500, unit: 'g' },
      { name: 'Pains à burger briochés', quantity: 4, unit: 'pièce' },
      { name: 'Cheddar en tranches', quantity: 4, unit: 'pièce' },
      { name: 'Laitue', quantity: 4, unit: 'feuille' },
      { name: 'Tomate', quantity: 1, unit: 'pièce' },
      { name: 'Oignon rouge', quantity: 1, unit: 'pièce' },
      { name: 'Cornichons', quantity: 8, unit: 'tranche' },
    ],
    preparation: `1. Formez 4 steaks hachés. Salez et poivrez généreusement.\n2. Faites cuire les steaks dans une poêle chaude, 3-4 minutes de chaque côté pour une cuisson à point.\n3. Pendant la dernière minute de cuisson, placez une tranche de cheddar sur chaque steak et couvrez pour faire fondre.\n4. Faites toaster légèrement les pains à burger.\n5. Assemblez : pain inférieur, sauce de votre choix, laitue, tomate, steak avec fromage, oignon, cornichons, pain supérieur.`
  },
  {
    id: 'r13',
    title: 'Houmous et Pain Pita',
    description: 'Une trempette crémeuse de pois chiches du Moyen-Orient, parfaite en apéritif ou en repas léger.',
    country: 'Liban',
    calories: 400,
    portions: 4,
    preparationTime: 10,
    isEconomical: true,
    ingredients: [
      { name: 'Pois chiches en conserve', quantity: 400, unit: 'g' },
      { name: 'Tahini (purée de sésame)', quantity: 4, unit: 'cuillère à soupe' },
      { name: 'Jus de citron', quantity: 1, unit: 'pièce' },
      { name: 'Ail', quantity: 1, unit: 'gousse' },
      { name: 'Huile d\'olive', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Paprika', quantity: 1, unit: 'cuillère à café' },
      { name: 'Pains pita', quantity: 4, unit: 'pièce' },
    ],
    preparation: `1. Rincez et égouttez les pois chiches. Gardez un peu de leur eau.\n2. Dans un mixeur, mettez les pois chiches, le tahini, le jus de citron et l'ail. Mixez jusqu'à obtenir une pâte.\n3. Tout en mixant, versez un filet d'eau des pois chiches jusqu'à la consistance désirée.\n4. Servez dans un bol, créez un tourbillon avec une cuillère, arrosez d'huile d'olive et saupoudrez de paprika.\n5. Dégustez avec des pains pita tièdes.`
  },
  {
    id: 'r14',
    title: 'Salade César',
    description: 'Une salade croquante et savoureuse, un classique indémodable.',
    country: 'Mexique / USA',
    calories: 550,
    portions: 2,
    preparationTime: 20,
    isEconomical: false,
    ingredients: [
      { name: 'Filet de Poulet', quantity: 200, unit: 'g' },
      { name: 'Laitue', quantity: 1, unit: 'pièce' },
      { name: 'Croûtons', quantity: 50, unit: 'g' },
      { name: 'Parmesan', quantity: 30, unit: 'g' },
      { name: 'Oeufs', quantity: 1, unit: 'pièce' },
      { name: 'Ail', quantity: 1, unit: 'gousse' },
      { name: 'Huile d\'olive', quantity: 50, unit: 'ml' },
      { name: 'Citron', quantity: 1, unit: 'pièce' },
    ],
    preparation: `1. Faites griller le filet de poulet, puis coupez-le en lanières.\n2. Préparez la sauce César : émulsionnez un jaune d'œuf avec l'ail haché, le jus de citron et montez à l'huile d'olive. Incorporez la moitié du parmesan râpé.\n3. Lavez et coupez la laitue. Mettez-la dans un saladier.\n4. Ajoutez le poulet, les croûtons et le reste du parmesan en copeaux.\n5. Versez la sauce, mélangez délicatement et servez immédiatement.`
  },
  {
    id: 'r15',
    title: 'Couscous Tunisien à l\'Agneau',
    description: 'Un plat familial généreux et parfumé, emblème de la cuisine tunisienne.',
    country: 'Tunisie',
    calories: 900,
    portions: 6,
    preparationTime: 120,
    isEconomical: false,
    ingredients: [
      { name: 'Gigot d\'agneau', quantity: 800, unit: 'g' },
      { name: 'Semoule de couscous', quantity: 500, unit: 'g' },
      { name: 'Pois chiches en conserve', quantity: 200, unit: 'g' },
      { name: 'Carottes', quantity: 4, unit: 'pièce' },
      { name: 'Courgettes', quantity: 2, unit: 'pièce' },
      { name: 'Navets', quantity: 2, unit: 'pièce' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Concentré de tomate', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Harissa en conserve', quantity: 1, unit: 'cuillère à soupe' },
      { name: 'Huile d\'olive', quantity: 50, unit: 'ml' },
    ],
    preparation: `1. Dans le bas d'un couscoussier, faites revenir l'oignon haché et les morceaux d'agneau dans l'huile d'olive.\n2. Ajoutez le concentré de tomate, l'harissa, du sel, du poivre et couvrez d'eau. Laissez mijoter 45 minutes.\n3. Pendant ce temps, préparez la semoule en l'arrosant d'un peu d'eau salée et d'huile, et en l'égrainant à la main.\n4. Ajoutez les légumes coupés en gros morceaux (carottes, navets) dans le bouillon. Placez la semoule dans le haut du couscoussier et laissez cuire à la vapeur 20 minutes.\n5. Ajoutez les courgettes et les pois chiches au bouillon. Remélangez la semoule et remettez à cuire 15 minutes.\n6. Servez la semoule dans un grand plat, creusez un puits, disposez la viande et les légumes et arrosez de bouillon.`
  },
  {
    id: 'r16',
    title: 'Pizza Margherita',
    description: 'La reine des pizzas, simple, aux couleurs de l\'Italie, un vrai délice.',
    country: 'Italie',
    calories: 750,
    portions: 1,
    preparationTime: 25,
    isEconomical: true,
    ingredients: [
      { name: 'Pâte à pizza', quantity: 1, unit: 'pièce' },
      { name: 'Tomates pelées', quantity: 200, unit: 'g' },
      { name: 'Mozzarella', quantity: 150, unit: 'g' },
      { name: 'Basilic frais', quantity: 1, unit: 'botte' },
      { name: 'Huile d\'olive', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Sel', quantity: 1, unit: 'pincée' },
    ],
    preparation: `1. Préchauffez votre four à la température maximale (250°C ou plus).\n2. Étalez la pâte à pizza sur une plaque de cuisson.\n3. Mixez les tomates pelées avec du sel et un filet d'huile d'olive pour faire la sauce. Étalez-la sur la pâte.\n4. Coupez la mozzarella en tranches et répartissez-la sur la pizza.\n5. Enfournez pour 10-12 minutes, jusqu'à ce que la croûte soit dorée et le fromage bien fondu.\n6. À la sortie du four, parsemez de feuilles de basilic frais et d'un filet d'huile d'olive.`
  },
  {
    id: 'r17',
    title: 'Chili con Carne',
    description: 'Un plat tex-mex riche et épicé, réconfortant et parfait à partager.',
    country: 'USA / Mexique',
    calories: 600,
    portions: 6,
    preparationTime: 90,
    isEconomical: true,
    ingredients: [
      { name: 'Bœuf haché', quantity: 500, unit: 'g' },
      { name: 'Haricots rouges en conserve', quantity: 400, unit: 'g' },
      { name: 'Tomates pelées', quantity: 400, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Ail', quantity: 2, unit: 'gousse' },
      { name: 'Poivron', quantity: 1, unit: 'pièce' },
      { name: 'Piment en poudre', quantity: 2, unit: 'cuillère à café' },
      { name: 'Cumin en poudre', quantity: 1, unit: 'cuillère à café' },
    ],
    preparation: `1. Hachez l'oignon, l'ail et le poivron. Faites-les revenir dans une grande cocotte avec un peu d'huile.\n2. Ajoutez le bœuf haché et faites-le dorer en l'émiettant.\n3. Incorporez les épices (piment, cumin), salez et poivrez. Mélangez bien.\n4. Ajoutez les tomates pelées (et leur jus) et les haricots rouges égouttés.\n5. Portez à ébullition, puis baissez le feu et laissez mijoter à couvert pendant au moins 1 heure.\n6. Servez chaud avec du riz, du fromage râpé ou de la crème fraîche.`
  },
  {
    id: 'r18',
    title: 'Ratatouille Niçoise',
    description: 'Un plat d\'été provençal, plein de légumes du soleil mijotés longuement.',
    country: 'France',
    calories: 300,
    portions: 4,
    preparationTime: 75,
    isEconomical: true,
    ingredients: [
      { name: 'Aubergine', quantity: 2, unit: 'pièce' },
      { name: 'Courgette', quantity: 2, unit: 'pièce' },
      { name: 'Poivron', quantity: 2, unit: 'pièce' },
      { name: 'Tomates', quantity: 4, unit: 'pièce' },
      { name: 'Oignon', quantity: 2, unit: 'pièce' },
      { name: 'Ail', quantity: 3, unit: 'gousse' },
      { name: 'Huile d\'olive', quantity: 4, unit: 'cuillère à soupe' },
      { name: 'Bouquet garni', quantity: 1, unit: 'pièce' },
    ],
    preparation: `1. Coupez tous les légumes en morceaux de taille similaire.\n2. Faites revenir chaque légume séparément dans l'huile d'olive et réservez-les. Cela permet à chaque légume de développer sa propre saveur.\n3. Une fois tous les légumes précuits, faites revenir les oignons et l'ail hachés dans la même cocotte.\n4. Ajoutez les tomates et le bouquet garni. Laissez compoter 15 minutes.\n5. Remettez tous les légumes dans la cocotte. Salez, poivrez, et mélangez délicatement.\n6. Laissez mijoter à feu très doux et à couvert pendant au moins 45 minutes. La ratatouille est encore meilleure réchauffée.`
  },
  {
    id: 'r19',
    title: 'Omelette Rapide aux Fines Herbes',
    description: 'Un classique simple, rapide et économique pour un repas léger.',
    country: 'France',
    calories: 300,
    portions: 1,
    preparationTime: 10,
    isEconomical: true,
    ingredients: [
      { name: 'Oeufs', quantity: 3, unit: 'pièce' },
      { name: 'Lait', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Ciboulette fraîche', quantity: 1, unit: 'cuillère à soupe' },
      { name: 'Persil frais', quantity: 1, unit: 'cuillère à soupe' },
      { name: 'Beurre', quantity: 10, unit: 'g' },
      { name: 'Sel et Poivre', quantity: 1, unit: 'pincée' },
    ],
    preparation: `1. Cassez les œufs dans un bol. Ajoutez le lait, le sel et le poivre. Fouettez énergiquement.\n2. Ciselez finement les herbes et ajoutez-les au mélange.\n3. Faites fondre le beurre dans une poêle chaude. Versez les œufs.\n4. Laissez cuire à feu moyen en ramenant les bords vers le centre.\n5. Une fois que l'omelette est presque prise mais encore baveuse sur le dessus, pliez-la en deux et servez immédiatement.`
  },
  {
    id: 'r20',
    title: 'Salade de Lentilles',
    description: 'Une salade saine, nourrissante et économique, parfaite pour un déjeuner à emporter.',
    country: 'International',
    calories: 400,
    portions: 4,
    preparationTime: 30,
    isEconomical: true,
    ingredients: [
      { name: 'Lentilles vertes', quantity: 250, unit: 'g' },
      { name: 'Oignon rouge', quantity: 1, unit: 'pièce' },
      { name: 'Carottes', quantity: 1, unit: 'pièce' },
      { name: 'Vinaigrette', quantity: 4, unit: 'cuillère à soupe' },
      { name: 'Persil frais', quantity: 2, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Faites cuire les lentilles dans un grand volume d'eau pendant 20-25 minutes. Elles doivent être tendres mais pas en purée. Égouttez-les.\n2. Pendant ce temps, coupez la carotte en petits dés et émincez finement l'oignon rouge.\n3. Dans un saladier, mélangez les lentilles encore tièdes avec les carottes, l'oignon et le persil ciselé.\n4. Arrosez de vinaigrette, mélangez bien et laissez refroidir. Se conserve très bien au réfrigérateur.`
  },
  {
    id: 'r21',
    title: 'Gaspacho Andalou',
    description: 'Une soupe froide espagnole rafraîchissante, parfaite pour les chaudes journées d\'été.',
    country: 'Espagne',
    calories: 150,
    portions: 4,
    preparationTime: 15,
    isEconomical: true,
    ingredients: [
      { name: 'Tomates mûres', quantity: 1, unit: 'kg' },
      { name: 'Concombre', quantity: 1, unit: 'pièce' },
      { name: 'Poivron vert', quantity: 1, unit: 'pièce' },
      { name: 'Oignon', quantity: 0.5, unit: 'pièce' },
      { name: 'Ail', quantity: 1, unit: 'gousse' },
      { name: 'Huile d\'olive', quantity: 50, unit: 'ml' },
      { name: 'Vinaigre de Xérès', quantity: 2, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Lavez et coupez tous les légumes en gros morceaux.\n2. Mettez-les dans un blender puissant.\n3. Ajoutez l'ail, l'huile d'olive, le vinaigre, le sel et un peu d'eau froide.\n4. Mixez jusqu'à obtenir une consistance lisse et homogène.\n5. Passez le gaspacho au chinois si vous le souhaitez plus fin.\n6. Réservez au réfrigérateur au moins 2 heures avant de servir bien frais.`
  },
  {
    id: 'r22',
    title: 'Poulet Yassa',
    description: 'Un plat sénégalais emblématique, du poulet mariné dans une sauce aux oignons et au citron.',
    country: 'Sénégal',
    calories: 500,
    portions: 6,
    preparationTime: 75,
    isEconomical: true,
    ingredients: [
      { name: 'Poulet en morceaux', quantity: 1, unit: 'kg' },
      { name: 'Oignons', quantity: 4, unit: 'pièce' },
      { name: 'Citrons', quantity: 3, unit: 'pièce' },
      { name: 'Moutarde de Dijon', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Ail', quantity: 3, unit: 'gousse' },
      { name: 'Huile d\'arachide', quantity: 4, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Émincez finement les oignons. Préparez la marinade avec le jus des citrons, la moutarde, l'ail haché, du sel et du poivre.\n2. Mélangez le poulet avec les oignons et la marinade. Laissez mariner au moins 2 heures (idéalement une nuit).\n3. Retirez les morceaux de poulet et faites-les griller au barbecue ou à la poêle.\n4. Dans une cocotte, faites revenir les oignons de la marinade dans l'huile. Une fois bien fondus, ajoutez le reste de la marinade et un peu d'eau.\n5. Remettez le poulet grillé dans la sauce et laissez mijoter 30 minutes. Servez avec du riz blanc.`
  },
  {
    id: 'r23',
    title: 'Crevettes à l\'Ail (Gambas al Ajillo)',
    description: 'Un tapa espagnol classique, rapide, simple et incroyablement savoureux.',
    country: 'Espagne',
    calories: 350,
    portions: 2,
    preparationTime: 10,
    isEconomical: false,
    ingredients: [
      { name: 'Crevettes crues décortiquées', quantity: 400, unit: 'g' },
      { name: 'Ail', quantity: 5, unit: 'gousse' },
      { name: 'Piment de Cayenne séché', quantity: 1, unit: 'pièce' },
      { name: 'Huile d\'olive', quantity: 100, unit: 'ml' },
      { name: 'Persil frais haché', quantity: 2, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Émincez finement l'ail.\n2. Dans une poêle en terre cuite (ou une poêle normale), faites chauffer l'huile d'olive à feu moyen.\n3. Ajoutez l'ail et le piment. Faites-les revenir sans les brûler jusqu'à ce que l'ail soit parfumé.\n4. Augmentez le feu, ajoutez les crevettes. Faites-les cuire 2-3 minutes en remuant, jusqu'à ce qu'elles deviennent roses.\n5. Retirez du feu, salez, parsemez de persil et servez immédiatement avec du pain pour saucer.`
  },
  {
    id: 'r24',
    title: 'Dahl de Lentilles Corail',
    description: 'Un plat indien végétarien crémeux, parfumé et très réconfortant. Parfait avec du riz ou du naan.',
    country: 'Inde',
    calories: 450,
    portions: 4,
    preparationTime: 25,
    isEconomical: true,
    ingredients: [
      { name: 'Lentilles corail', quantity: 200, unit: 'g' },
      { name: 'Lait de coco', quantity: 200, unit: 'ml' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Ail', quantity: 2, unit: 'gousse' },
      { name: 'Gingembre frais râpé', quantity: 1, unit: 'cuillère à café' },
      { name: 'Curcuma', quantity: 1, unit: 'cuillère à café' },
      { name: 'Cumin en poudre', quantity: 1, unit: 'cuillère à café' },
    ],
    preparation: `1. Rincez les lentilles corail.\n2. Dans une casserole, faites revenir l'oignon haché, l'ail et le gingembre.\n3. Ajoutez les épices (curcuma, cumin) et faites-les torréfier 1 minute.\n4. Ajoutez les lentilles, 500ml d'eau et portez à ébullition. Laissez mijoter 15 minutes.\n5. Versez le lait de coco, salez et poursuivez la cuisson 5 minutes jusqu'à ce que le dahl soit crémeux.\n6. Servez chaud, garni de coriandre fraîche.`
  },
  {
    id: 'r25',
    title: 'Bruschetta Tomate Basilic',
    description: 'L\'antipasto italien par excellence. Frais, simple et plein de saveurs.',
    country: 'Italie',
    calories: 250,
    portions: 4,
    preparationTime: 15,
    isEconomical: true,
    ingredients: [
      { name: 'Baguette ou pain de campagne', quantity: 4, unit: 'tranche' },
      { name: 'Tomates cerises', quantity: 250, unit: 'g' },
      { name: 'Ail', quantity: 1, unit: 'gousse' },
      { name: 'Basilic frais', quantity: 1, unit: 'botte' },
      { name: 'Huile d\'olive extra vierge', quantity: 3, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Faites griller les tranches de pain.\n2. Frottez la surface de chaque tranche avec la gousse d'ail coupée en deux.\n3. Coupez les tomates en petits dés. Ciselez le basilic.\n4. Dans un bol, mélangez les tomates, le basilic, l'huile d'olive, le sel et le poivre.\n5. Garnissez généreusement les tranches de pain avec la préparation aux tomates.\n6. Servez immédiatement.`
  },
  {
    id: 'r26',
    title: 'Soupe à l\'Oignon Gratinée',
    description: 'Un classique de la bistronomie française, réconfortant et gourmand.',
    country: 'France',
    calories: 450,
    portions: 4,
    preparationTime: 60,
    isEconomical: true,
    ingredients: [
      { name: 'Oignons', quantity: 500, unit: 'g' },
      { name: 'Bouillon de bœuf', quantity: 1, unit: 'L' },
      { name: 'Beurre', quantity: 30, unit: 'g' },
      { name: 'Farine', quantity: 1, unit: 'cuillère à soupe' },
      { name: 'Baguette', quantity: 4, unit: 'tranche' },
      { name: 'Fromage Gruyère râpé', quantity: 100, unit: 'g' },
    ],
    preparation: `1. Émincez finement les oignons. Faites-les fondre doucement dans le beurre pendant 20-30 minutes jusqu'à ce qu'ils soient bien caramélisés.\n2. Saupoudrez de farine, mélangez bien et laissez cuire 1 minute.\n3. Déglacez avec un peu de vin blanc (facultatif), puis versez le bouillon de bœuf chaud. Laissez mijoter 20 minutes.\n4. Répartissez la soupe dans des bols allant au four. Déposez une tranche de pain rassis sur le dessus.\n5. Couvrez généreusement de fromage râpé et passez sous le gril du four jusqu'à ce que le fromage soit doré et bouillonnant.`
  },
  {
    id: 'r27',
    title: 'Goulash Hongrois',
    description: 'Un ragoût de bœuf riche et parfumé au paprika, le plat national de la Hongrie.',
    country: 'Hongrie',
    calories: 600,
    portions: 6,
    preparationTime: 150,
    isEconomical: false,
    ingredients: [
      { name: 'Bœuf à braiser', quantity: 800, unit: 'g' },
      { name: 'Oignons', quantity: 3, unit: 'pièce' },
      { name: 'Paprika doux de Hongrie', quantity: 3, unit: 'cuillère à soupe' },
      { name: 'Carottes', quantity: 2, unit: 'pièce' },
      { name: 'Pommes de terre', quantity: 3, unit: 'pièce' },
      { name: 'Bouillon de bœuf', quantity: 750, unit: 'ml' },
    ],
    preparation: `1. Coupez le bœuf en cubes. Hachez les oignons.\n2. Dans une cocotte, faites revenir les oignons dans l'huile ou le saindoux jusqu'à ce qu'ils soient translucides.\n3. Hors du feu, ajoutez le paprika et mélangez rapidement. Ajoutez le bœuf et faites-le dorer sur toutes les faces.\n4. Versez le bouillon, salez, poivrez. Laissez mijoter à couvert pendant au moins 2 heures.\n5. Ajoutez les carottes et les pommes de terre coupées en dés. Poursuivez la cuisson 30-40 minutes, jusqu'à ce que les légumes et la viande soient tendres.`
  },
  {
    id: 'r28',
    title: 'Ceviche Péruvien',
    description: 'Du poisson cru "cuit" dans du jus de citron vert, un plat péruvien frais et acidulé.',
    country: 'Pérou',
    calories: 300,
    portions: 4,
    preparationTime: 20,
    isEconomical: false,
    ingredients: [
      { name: 'Filet de poisson blanc très frais (cabillaud, dorade)', quantity: 500, unit: 'g' },
      { name: 'Citrons verts', quantity: 5, unit: 'pièce' },
      { name: 'Oignon rouge', quantity: 1, unit: 'pièce' },
      { name: 'Piment (Aji Amarillo ou autre)', quantity: 1, unit: 'pièce' },
      { name: 'Coriandre fraîche', quantity: 1, unit: 'botte' },
      { name: 'Maïs doux et patate douce cuite', quantity: 1, unit: 'pour servir' },
    ],
    preparation: `1. Coupez le poisson en cubes de 1-2 cm. Émincez finement l'oignon rouge et le piment (sans les graines).\n2. Dans un bol en verre, mélangez le poisson, l'oignon, le piment et la coriandre ciselée.\n3. Pressez les citrons verts et versez le jus sur le poisson. Le jus doit presque recouvrir le poisson. Salez.\n4. Laissez mariner au réfrigérateur pendant 10-15 minutes, jusqu'à ce que le poisson devienne opaque.\n5. Servez immédiatement avec du maïs et des rondelles de patate douce.`
  },
  {
    id: 'r29',
    title: 'Feijoada',
    description: 'Le plat national brésilien, un ragoût copieux de haricots noirs et de différentes viandes de porc.',
    country: 'Brésil',
    calories: 950,
    portions: 8,
    preparationTime: 240,
    isEconomical: true,
    ingredients: [
      { name: 'Haricots noirs secs', quantity: 500, unit: 'g' },
      { name: 'Saucisses fumées', quantity: 200, unit: 'g' },
      { name: 'Poitrine de porc salée', quantity: 200, unit: 'g' },
      { name: 'Oignon', quantity: 2, unit: 'pièce' },
      { name: 'Ail', quantity: 4, unit: 'gousse' },
      { name: 'Feuilles de laurier', quantity: 3, unit: 'pièce' },
    ],
    preparation: `1. Faites tremper les haricots et la viande salée la veille.\n2. Le jour même, faites cuire les haricots dans une grande marmite d'eau. Ajoutez les viandes après 1 heure de cuisson.\n3. Laissez mijoter le tout pendant au moins 2-3 heures, jusqu'à ce que les haricots et les viandes soient très tendres.\n4. Dans une poêle, faites revenir l'oignon et l'ail hachés. Ajoutez une louche de haricots, écrasez-les et reversez ce mélange dans la marmite pour épaissir la sauce.\n5. Servez avec du riz blanc, des tranches d'orange et du chou vert sauté (couve).`
  },
  {
    id: 'r30',
    title: 'Fish and Chips',
    description: 'Le classique de la street-food britannique : du poisson frit dans une pâte à la bière, servi avec des frites épaisses.',
    country: 'Royaume-Uni',
    calories: 850,
    portions: 4,
    preparationTime: 40,
    isEconomical: false,
    ingredients: [
      { name: 'Filet de cabillaud ou d\'aiglefin', quantity: 4, unit: 'pièce' },
      { name: 'Farine', quantity: 200, unit: 'g' },
      { name: 'Bière blonde', quantity: 250, unit: 'ml' },
      { name: 'Levure chimique', quantity: 1, unit: 'cuillère à café' },
      { name: 'Pommes de terre', quantity: 1, unit: 'kg' },
      { name: 'Huile de friture', quantity: 1, unit: 'L' },
    ],
    preparation: `1. Préparez les frites : coupez les pommes de terre en bâtonnets épais. Faites-les précuire dans l'huile à 160°C pendant 5-7 minutes. Réservez.\n2. Préparez la pâte : mélangez la farine, la levure, le sel. Incorporez la bière froide pour obtenir une pâte lisse.\n3. Farinez légèrement les filets de poisson, puis trempez-les dans la pâte.\n4. Faites-les frire dans l'huile à 180°C pendant 5-8 minutes jusqu'à ce qu'ils soient bien dorés.\n5. Replongez les frites dans l'huile chaude pendant 2-3 minutes pour les rendre croustillantes.\n6. Servez immédiatement avec du sel, du vinaigre de malt et une purée de petits pois (mushy peas).`
  },
  {
    id: 'r31',
    title: 'Wiener Schnitzel',
    description: 'Une escalope de veau panée et frite, une spécialité viennoise croustillante et délicieuse.',
    country: 'Autriche',
    calories: 600,
    portions: 4,
    preparationTime: 20,
    isEconomical: false,
    ingredients: [
      { name: 'Escalopes de veau très fines', quantity: 4, unit: 'pièce' },
      { name: 'Farine', quantity: 100, unit: 'g' },
      { name: 'Oeufs', quantity: 2, unit: 'pièce' },
      { name: 'Chapelure fine', quantity: 150, unit: 'g' },
      { name: 'Beurre clarifié ou huile', quantity: 1, unit: 'pour la friture' },
    ],
    preparation: `1. Aplatissez encore les escalopes si nécessaire. Salez et poivrez.\n2. Préparez trois assiettes : une avec la farine, une avec les œufs battus, une avec la chapelure.\n3. Passez chaque escalope successivement dans la farine, l'œuf puis la chapelure, en veillant à bien la recouvrir.\n4. Faites chauffer une bonne quantité de matière grasse dans une grande poêle. L'escalope doit "nager".\n5. Faites frire chaque schnitzel 2-3 minutes de chaque côté jusqu'à ce qu'il soit doré et croustillant.\n6. Servez immédiatement avec une tranche de citron et une salade de pommes de terre.`
  },
  {
    id: 'r32',
    title: 'Bibimbap',
    description: 'Un bol de riz coréen coloré et sain, garni de légumes variés, de viande et d\'un œuf sur le plat.',
    country: 'Corée du Sud',
    calories: 650,
    portions: 4,
    preparationTime: 40,
    isEconomical: false,
    ingredients: [
      { name: 'Riz cuit', quantity: 4, unit: 'bol' },
      { name: 'Bœuf haché', quantity: 200, unit: 'g' },
      { name: 'Épinards', quantity: 100, unit: 'g' },
      { name: 'Carottes', quantity: 1, unit: 'pièce' },
      { name: 'Pousses de soja', quantity: 100, unit: 'g' },
      { name: 'Oeufs', quantity: 4, unit: 'pièce' },
      { name: 'Sauce Gochujang', quantity: 4, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Faites mariner le bœuf dans de la sauce soja et de l'huile de sésame, puis faites-le sauter.\n2. Préparez les légumes : blanchissez les épinards et les pousses de soja, coupez la carotte en julienne et faites-la sauter rapidement.\n3. Faites cuire quatre œufs au plat, en gardant le jaune coulant.\n4. Assemblez les bols : mettez une portion de riz chaud, disposez joliment les légumes et la viande sur le dessus. Terminez avec l'œuf.\n5. Servez avec la sauce Gochujang. Chaque convive mélange son bol avant de déguster.`
  },
  {
    id: 'r33',
    title: 'Pâtes au Pesto',
    description: 'Une recette italienne simple, rapide et débordante de la fraîcheur du basilic.',
    country: 'Italie',
    calories: 550,
    portions: 4,
    preparationTime: 15,
    isEconomical: true,
    ingredients: [
      { name: 'Pâtes (Trofie ou Trenette)', quantity: 400, unit: 'g' },
      { name: 'Basilic frais', quantity: 2, unit: 'gros bouquets' },
      { name: 'Pignons de pin', quantity: 30, unit: 'g' },
      { name: 'Parmesan râpé', quantity: 50, unit: 'g' },
      { name: 'Ail', quantity: 1, unit: 'gousse' },
      { name: 'Huile d\'olive extra vierge', quantity: 100, unit: 'ml' },
    ],
    preparation: `1. Faites cuire les pâtes.\n2. Pendant ce temps, préparez le pesto : mixez (ou pilez au mortier) le basilic, les pignons de pin, le parmesan, l'ail et le sel.\n3. Incorporez l'huile d'olive en filet pour obtenir une sauce onctueuse.\n4. Égouttez les pâtes en gardant un peu d'eau de cuisson.\n5. Mélangez les pâtes avec le pesto. Ajoutez un peu d'eau de cuisson pour délayer si nécessaire.\n6. Servez immédiatement avec un supplément de parmesan.`
  },
  {
    id: 'r34',
    title: 'Croque-Monsieur',
    description: 'Le sandwich parisien par excellence, gratiné et délicieusement régressif.',
    country: 'France',
    calories: 600,
    portions: 4,
    preparationTime: 15,
    isEconomical: true,
    ingredients: [
      { name: 'Pain de mie', quantity: 8, unit: 'tranche' },
      { name: 'Jambon blanc de qualité', quantity: 4, unit: 'tranche' },
      { name: 'Fromage Gruyère râpé', quantity: 150, unit: 'g' },
      { name: 'Beurre', quantity: 40, unit: 'g' },
      { name: 'Sauce béchamel', quantity: 200, unit: 'ml' },
    ],
    preparation: `1. Préchauffez le four en mode gril.\n2. Beurrez légèrement un côté de chaque tranche de pain de mie.\n3. Montez les sandwichs : pain (côté non beurré), une fine couche de béchamel, une tranche de jambon, du gruyère râpé, pain.\n4. Étalez le reste de la béchamel sur le dessus des sandwichs et parsemez généreusement de gruyère.\n5. Enfournez pour 5-10 minutes, jusqu'à ce que le dessus soit bien doré et gratiné. (Pour un Croque-Madame, ajoutez un œuf au plat sur le dessus après cuisson).`
  },
  {
    id: 'r35',
    title: 'Samosas aux Légumes',
    description: 'Des triangles croustillants indiens farcis d\'un mélange épicé de pommes de terre et de petits pois.',
    country: 'Inde',
    calories: 300,
    portions: 4,
    preparationTime: 45,
    isEconomical: true,
    ingredients: [
      { name: 'Feuilles de brick ou pâte à samosa', quantity: 10, unit: 'pièce' },
      { name: 'Pommes de terre', quantity: 2, unit: 'pièce' },
      { name: 'Petits pois (surgelés)', quantity: 100, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Garam masala', quantity: 1, unit: 'cuillère à café' },
      { name: 'Graines de cumin', quantity: 1, unit: 'cuillère à café' },
    ],
    preparation: `1. Faites cuire les pommes de terre et écrasez-les grossièrement. Faites cuire les petits pois.\n2. Faites revenir l'oignon haché et les graines de cumin. Ajoutez les épices, puis les pommes de terre et les petits pois. Mélangez bien la farce.\n3. Coupez les feuilles de brick en deux. Pliez chaque moitié pour former un cône.\n4. Remplissez le cône avec la farce et repliez pour former un triangle. Collez le bord avec un peu d'eau.\n5. Faites frire les samosas dans l'huile chaude jusqu'à ce qu'ils soient dorés et croustillants. Servez avec un chutney à la menthe.`
  },
  {
    id: 'r36',
    title: 'Avocado Toast',
    description: 'Le petit-déjeuner ou brunch tendance, simple, sain et délicieux.',
    country: 'International',
    calories: 350,
    portions: 2,
    preparationTime: 5,
    isEconomical: false,
    ingredients: [
      { name: 'Pain de campagne de qualité', quantity: 2, unit: 'tranche' },
      { name: 'Avocat mûr', quantity: 1, unit: 'pièce' },
      { name: 'Jus de citron', quantity: 1, unit: 'cuillère à café' },
      { name: 'Flocons de piment', quantity: 1, unit: 'pincée' },
      { name: 'Fleur de sel', quantity: 1, unit: 'pincée' },
    ],
    preparation: `1. Faites griller les tranches de pain.\n2. Pendant ce temps, écrasez la chair de l'avocat à la fourchette dans un bol. Ajoutez le jus de citron, le sel et les flocons de piment. Mélangez.\n3. Étalez généreusement la purée d'avocat sur les toasts chauds.\n4. Dégustez immédiatement. (Options : ajoutez un œuf poché, des graines de sésame, ou des tomates cerises).`
  },
  {
    id: 'r37',
    title: 'Quesadillas au Fromage',
    description: 'Une collation mexicaine rapide et réconfortante, parfaite pour les enfants et les adultes.',
    country: 'Mexique',
    calories: 400,
    portions: 2,
    preparationTime: 10,
    isEconomical: true,
    ingredients: [
      { name: 'Tortillas de blé', quantity: 4, unit: 'pièce' },
      { name: 'Fromage râpé (Oaxaca, cheddar ou mozzarella)', quantity: 200, unit: 'g' },
      { name: 'Beurre ou huile', quantity: 1, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Faites chauffer une poêle à feu moyen. Beurrez ou huilez légèrement.\n2. Déposez une tortilla dans la poêle. Parsemez la moitié de la tortilla de fromage râpé.\n3. Repliez l'autre moitié de la tortilla par-dessus le fromage.\n4. Faites cuire 2-3 minutes de chaque côté, en appuyant avec une spatule, jusqu'à ce que la tortilla soit dorée et que le fromage soit bien fondu.\n5. Répétez avec les autres tortillas. Coupez en triangles et servez avec de la salsa, du guacamole ou de la crème fraîche.`
  },
  {
    id: 'r38',
    title: 'Salade de Concombre Asiatique',
    description: 'Une salade croquante et rafraîchissante, avec une vinaigrette savoureuse.',
    country: 'Chine',
    calories: 150,
    portions: 2,
    preparationTime: 10,
    isEconomical: true,
    ingredients: [
      { name: 'Concombre', quantity: 2, unit: 'pièce' },
      { name: 'Sauce soja', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Vinaigre de riz', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Huile de sésame', quantity: 1, unit: 'cuillère à café' },
      { name: 'Ail', quantity: 1, unit: 'gousse' },
      { name: 'Graines de sésame grillées', quantity: 1, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Lavez les concombres. Écrasez-les légèrement avec le plat d'un couteau pour les fendre, puis coupez-les en morceaux irréguliers.\n2. Mettez les morceaux de concombre dans un bol et saupoudrez d'un peu de sel. Laissez dégorger 5 minutes.\n3. Pendant ce temps, préparez la vinaigrette en mélangeant la sauce soja, le vinaigre, l'huile de sésame et l'ail haché.\n4. Égouttez l'excès d'eau des concombres.\n5. Versez la vinaigrette sur les concombres, ajoutez les graines de sésame et mélangez bien. Servez frais.`
  },
  {
    id: 'r39',
    title: 'Shakshuka',
    description: 'Des œufs pochés dans une sauce tomate épicée, un plat convivial originaire du Moyen-Orient et d\'Afrique du Nord.',
    country: 'Moyen-Orient / Tunisie',
    calories: 400,
    portions: 2,
    preparationTime: 25,
    isEconomical: true,
    ingredients: [
      { name: 'Oeufs', quantity: 4, unit: 'pièce' },
      { name: 'Tomates pelées en conserve', quantity: 800, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Poivron rouge', quantity: 1, unit: 'pièce' },
      { name: 'Ail', quantity: 2, unit: 'gousse' },
      { name: 'Cumin en poudre', quantity: 1, unit: 'cuillère à café' },
      { name: 'Paprika', quantity: 1, unit: 'cuillère à café' },
      { name: 'Feta', quantity: 50, unit: 'g' },
    ],
    preparation: `1. Faites revenir l'oignon et le poivron émincés dans une grande poêle avec de l'huile d'olive.\n2. Ajoutez l'ail et les épices. Faites cuire 1 minute.\n3. Versez les tomates, écrasez-les et laissez mijoter la sauce pendant 10-15 minutes pour qu'elle épaississe.\n4. Avec une cuillère, faites 4 puits dans la sauce. Cassez un œuf dans chaque puits.\n5. Couvrez la poêle et laissez cuire 5-8 minutes, jusqu'à ce que les blancs d'œufs soient pris mais les jaunes encore coulants.\n6. Parsemez de feta émiettée et de coriandre ou persil frais. Servez avec du pain.`
  },
  {
    id: 'r40',
    title: 'Salade Niçoise',
    description: 'Une salade-repas complète et colorée, emblématique de la cuisine du sud de la France.',
    country: 'France',
    calories: 500,
    portions: 2,
    preparationTime: 30,
    isEconomical: false,
    ingredients: [
      { name: 'Laitue', quantity: 1, unit: 'pièce' },
      { name: 'Thon en conserve à l\'huile', quantity: 180, unit: 'g' },
      { name: 'Tomates', quantity: 4, unit: 'pièce' },
      { name: 'Oeufs durs', quantity: 2, unit: 'pièce' },
      { name: 'Anchois', quantity: 4, unit: 'filet' },
      { name: 'Olives noires de Nice', quantity: 50, unit: 'g' },
      { name: 'Poivron vert', quantity: 1, unit: 'pièce' },
    ],
    preparation: `1. Préparez tous les ingrédients : lavez la salade, coupez les tomates en quartiers, écaillez les œufs, émincez le poivron.\n2. Dans un grand plat, disposez un lit de salade.\n3. Répartissez harmonieusement les tomates, le poivron, le thon émietté, les œufs coupés en quartiers, les olives et les filets d'anchois.\n4. Arrosez généreusement d'une vinaigrette à l'huile d'olive et au vinaigre de vin. Ne mélangez pas avant de servir.`
  },
  {
    id: 'r41',
    title: 'Ojja aux Merguez',
    description: 'Un classique tunisien épicé et réconfortant, des œufs pochés dans une sauce tomate pimentée aux merguez.',
    country: 'Tunisie',
    calories: 600,
    portions: 2,
    preparationTime: 20,
    isEconomical: true,
    ingredients: [
      { name: 'Oeufs', quantity: 4, unit: 'pièce' },
      { name: 'Merguez', quantity: 6, unit: 'pièce' },
      { name: 'Tomates fraîches ou pulpe', quantity: 400, unit: 'g' },
      { name: 'Harissa en conserve', quantity: 1, unit: 'cuillère à soupe' },
      { name: 'Ail', quantity: 3, unit: 'gousse' },
      { name: 'Huile d\'olive', quantity: 3, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Coupez les merguez en morceaux et faites-les dorer dans une poêle avec l'huile d'olive.\n2. Ajoutez l'ail haché et l'harissa. Faites chauffer 1 minute.\n3. Versez les tomates, salez, poivrez et laissez mijoter 10 minutes pour réduire la sauce.\n4. Cassez les œufs par-dessus la préparation.\n5. Couvrez et laissez cuire 3-5 minutes jusqu'à ce que les blancs soient pris.\n6. Dégustez avec du pain frais tunisien.`
  },
  {
    id: 'r42',
    title: 'Risotto aux Champignons',
    description: 'Un riz crémeux à l\'italienne, parfumé aux champignons et au parmesan.',
    country: 'Italie',
    calories: 550,
    portions: 4,
    preparationTime: 35,
    isEconomical: false,
    ingredients: [
      { name: 'Riz Arborio ou Carnaroli', quantity: 320, unit: 'g' },
      { name: 'Champignons de Paris', quantity: 400, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Bouillon de légumes', quantity: 1.2, unit: 'L' },
      { name: 'Beurre', quantity: 50, unit: 'g' },
      { name: 'Parmesan râpé', quantity: 60, unit: 'g' },
    ],
    preparation: `1. Faites chauffer le bouillon.\n2. Faites revenir l'oignon haché dans un peu de beurre. Ajoutez les champignons émincés et faites-les dorer.\n3. Versez le riz et nacrez-le jusqu'à ce qu'il soit translucide.\n4. Ajoutez le bouillon louche après louche, en attendant que le liquide soit absorbé avant d'en remettre.\n5. Une fois le riz cuit (environ 18-20 min), retirez du feu.\n6. Ajoutez le reste du beurre et le parmesan. Mélangez énergiquement (mantecatura) et servez.`
  },
  {
    id: 'r43',
    title: 'Chorba Frik',
    description: 'La soupe traditionnelle tunisienne, riche et parfumée, préparée avec du blé concassé (frik).',
    country: 'Tunisie',
    calories: 450,
    portions: 4,
    preparationTime: 50,
    isEconomical: true,
    ingredients: [
      { name: 'Viande d\'agneau ou bœuf', quantity: 200, unit: 'g' },
      { name: 'Frik (blé concassé vert)', quantity: 150, unit: 'g' },
      { name: 'Concentré de tomate', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Céleri haché', quantity: 1, unit: 'tasse' },
      { name: 'Huile d\'olive', quantity: 3, unit: 'cuillère à soupe' },
      { name: 'Coriandre et menthe séchée', quantity: 1, unit: 'pincée' },
    ],
    preparation: `1. Coupez la viande en petits dés. Faites-la revenir avec l'oignon et le céleri dans l'huile.\n2. Ajoutez le concentré de tomate et un peu de paprika. Couvrez d'eau (environ 1.5L).\n3. Laissez bouillir. Rincez le frik et ajoutez-le dans la marmite.\n4. Laissez cuire à feu moyen pendant 40 minutes en remuant de temps en temps.\n5. En fin de cuisson, ajoutez la coriandre et la menthe. Servez avec un quartier de citron.`
  },
  {
    id: 'r44',
    title: 'Falafels Maison',
    description: 'Des boulettes de pois chiches frites, croustillantes à l\'extérieur et moelleuses à l\'intérieur.',
    country: 'Liban / Moyen-Orient',
    calories: 350,
    portions: 4,
    preparationTime: 40,
    isEconomical: true,
    ingredients: [
      { name: 'Pois chiches secs (trempés la veille)', quantity: 500, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Ail', quantity: 3, unit: 'gousse' },
      { name: 'Coriandre fraîche', quantity: 1, unit: 'botte' },
      { name: 'Persil frais', quantity: 1, unit: 'botte' },
      { name: 'Cumin en poudre', quantity: 2, unit: 'cuillère à café' },
    ],
    preparation: `1. Mixez les pois chiches (non cuits !), l'oignon, l'ail et les herbes jusqu'à obtenir une pâte granuleuse.\n2. Ajoutez les épices et le sel. Laissez reposer la pâte au frais 1 heure.\n3. Formez de petites boules ou des disques avec vos mains.\n4. Faites frire dans l'huile chaude jusqu'à ce qu'ils soient bien bruns.\n5. Servez avec une sauce au tahini, dans un pain pita ou sur une salade.`
  },
  {
    id: 'r45',
    title: 'Slata Mechouia',
    description: 'La salade de légumes grillés tunisienne, fumée et relevée, un incontournable de la table.',
    country: 'Tunisie',
    calories: 200,
    portions: 4,
    preparationTime: 30,
    isEconomical: true,
    ingredients: [
      { name: 'Poivrons doux', quantity: 6, unit: 'pièce' },
      { name: 'Piments forts (selon goût)', quantity: 2, unit: 'pièce' },
      { name: 'Tomates', quantity: 3, unit: 'pièce' },
      { name: 'Ail', quantity: 4, unit: 'gousse' },
      { name: 'Thon en conserve', quantity: 1, unit: 'boîte' },
      { name: 'Huile d\'olive', quantity: 5, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Faites griller les poivrons, piments, tomates et gousses d'ail sur un grill ou au four jusqu'à ce que la peau noircisse.\n2. Placez les légumes dans un sac plastique quelques minutes pour faciliter l'épluchage.\n3. Enlevez la peau et les graines. Hachez grossièrement le tout au couteau ou au pilon (éviter le mixeur pour garder de la texture).\n4. Assaisonnez avec l'huile d'olive, du sel et du tabil (épices tunisiennes).\n5. Décorez avec du thon, des œufs durs et des olives avant de servir.`
  },
  {
    id: 'r46',
    title: 'Lasagnes à la Bolognaise',
    description: 'Le gratin de pâtes italien familial, avec une sauce bolognaise mijotée et une béchamel crémeuse.',
    country: 'Italie',
    calories: 800,
    portions: 6,
    preparationTime: 90,
    isEconomical: false,
    ingredients: [
      { name: 'Feuilles de lasagnes', quantity: 1, unit: 'paquet' },
      { name: 'Bœuf haché', quantity: 500, unit: 'g' },
      { name: 'Tomates pelées', quantity: 800, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Sauce béchamel', quantity: 500, unit: 'ml' },
      { name: 'Fromage râpé', quantity: 150, unit: 'g' },
    ],
    preparation: `1. Préparez la bolognaise : faites revenir l'oignon, ajoutez le bœuf puis les tomates. Laissez mijoter 30 minutes.\n2. Dans un plat allant au four, étalez un peu de béchamel au fond.\n3. Alternez : feuilles de lasagnes, bolognaise, béchamel, fromage. Répétez 3-4 fois.\n4. Terminez par une couche de béchamel et beaucoup de fromage.\n5. Enfournez à 180°C pendant 30-40 minutes jusqu'à ce que le dessus soit bien gratiné.`
  },
  {
    id: 'r47',
    title: 'Salade Grecque (Horiatiki)',
    description: 'La fraîcheur de la Méditerranée : tomates, concombres, feta et olives.',
    country: 'Grèce',
    calories: 350,
    portions: 2,
    preparationTime: 10,
    isEconomical: true,
    ingredients: [
      { name: 'Tomates', quantity: 3, unit: 'pièce' },
      { name: 'Concombre', quantity: 1, unit: 'pièce' },
      { name: 'Oignon rouge', quantity: 0.5, unit: 'pièce' },
      { name: 'Feta', quantity: 150, unit: 'g' },
      { name: 'Olives Kalamata', quantity: 50, unit: 'g' },
      { name: 'Huile d\'olive', quantity: 4, unit: 'cuillère à soupe' },
    ],
    preparation: `1. Coupez les tomates en quartiers et le concombre en rondelles ou demi-lunes.\n2. Émincez finement l'oignon rouge.\n3. Mélangez les légumes dans un saladier.\n4. Posez une large tranche de feta par-dessus (ou coupez-la en dés).\n5. Ajoutez les olives. Arrosez d'huile d'olive, parsemez d'origan séché et servez.`
  },
  {
    id: 'r48',
    title: 'Lentilles à la Marocaine',
    description: 'Un ragoût de lentilles savoureux et épicé, souvent servi en accompagnement ou en plat principal végétarien.',
    country: 'Maroc',
    calories: 400,
    portions: 4,
    preparationTime: 35,
    isEconomical: true,
    ingredients: [
      { name: 'Lentilles brunes ou vertes', quantity: 250, unit: 'g' },
      { name: 'Tomates râpées', quantity: 2, unit: 'pièce' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Ail', quantity: 3, unit: 'gousse' },
      { name: 'Cumin et Paprika', quantity: 1, unit: 'cuillère à café' },
      { name: 'Coriandre fraîche', quantity: 1, unit: 'botte' },
    ],
    preparation: `1. Faites revenir l'oignon et l'ail dans l'huile d'olive.\n2. Ajoutez les tomates râpées et les épices. Laissez cuire 5 minutes.\n3. Incorporez les lentilles rincées et couvrez largement d'eau.\n4. Laissez mijoter environ 25-30 minutes jusqu'à ce que les lentilles soient fondantes et la sauce liée.\n5. Ajoutez la coriandre ciselée en fin de cuisson. Servez chaud avec du pain.`
  },
  {
    id: 'r49',
    title: 'Makarouna Bel Allouch',
    description: 'Les célèbres pâtes tunisiennes à la sauce tomate épicée et à la viande d\'agneau fondante.',
    country: 'Tunisie',
    calories: 850,
    portions: 4,
    preparationTime: 60,
    isEconomical: false,
    ingredients: [
      { name: 'Pâtes (type Penne ou Macaroni)', quantity: 500, unit: 'g' },
      { name: 'Viande d\'agneau', quantity: 600, unit: 'g' },
      { name: 'Concentré de tomate', quantity: 3, unit: 'cuillère à soupe' },
      { name: 'Harissa en conserve', quantity: 1, unit: 'cuillère à café' },
      { name: 'Piment vert', quantity: 2, unit: 'pièce' },
      { name: 'Laurier', quantity: 2, unit: 'feuille' },
    ],
    preparation: `1. Faites revenir la viande d'agneau et les oignons dans l'huile d'olive.\n2. Ajoutez le concentré de tomate, l'harissa et les feuilles de laurier. Laissez roussir 2 minutes.\n3. Couvrez d'eau chaude et laissez mijoter à feu moyen pendant 45 minutes.\n4. En fin de cuisson de la sauce, ajoutez les piments entiers. La sauce doit être épaisse et l'huile doit remonter en surface.\n5. Faites cuire les pâtes à l'eau salée, égouttez-les et mélangez-les avec la sauce. Servez avec la viande sur le dessus.`
  },
  {
    id: 'r50',
    title: 'Ratatouille au Four (Style Tian)',
    description: 'Une version élégante et colorée de la ratatouille, où les légumes sont disposés en rosace.',
    country: 'France',
    calories: 250,
    portions: 4,
    preparationTime: 60,
    isEconomical: true,
    ingredients: [
      { name: 'Courgette', quantity: 2, unit: 'pièce' },
      { name: 'Aubergine', quantity: 1, unit: 'pièce' },
      { name: 'Tomates', quantity: 4, unit: 'pièce' },
      { name: 'Poivron', quantity: 1, unit: 'pièce' },
      { name: 'Huile d\'olive', quantity: 5, unit: 'cuillère à soupe' },
      { name: 'Ail', quantity: 2, unit: 'gousse' },
    ],
    preparation: `1. Préchauffez le four à 180°C.\n2. Coupez tous les légumes en rondelles de même épaisseur.\n3. Dans un plat à gratin, alternez les rondelles de légumes en les serrant bien (courgette, tomate, aubergine, poivron...).\n4. Arrosez généreusement d'huile d'olive mélangée à de l'ail haché et des herbes de Provence.\n5. Enfournez pour 45-50 minutes jusqu'à ce que les légumes soient tendres et légèrement caramélisés.`
  },
  {
    id: 'r51',
    title: 'Khachapuri Adjaruli',
    description: 'Un "bateau" de pain géorgien rempli de fromage fondant et surmonté d\'un œuf et de beurre.',
    country: 'Géorgie',
    calories: 850,
    portions: 2,
    preparationTime: 45,
    isEconomical: true,
    ingredients: [
      { name: 'Pâte à pain', quantity: 400, unit: 'g' },
      { name: 'Mozzarella râpée', quantity: 200, unit: 'g' },
      { name: 'Feta ou Sulguni', quantity: 200, unit: 'g' },
      { name: 'Oeufs', quantity: 2, unit: 'pièce' },
      { name: 'Beurre', quantity: 20, unit: 'g' },
    ],
    preparation: `1. Préchauffez le four à 220°C.\n2. Divisez la pâte en deux et étalez-la en ovale. Roulez les bords vers le centre pour former un bateau.\n3. Mélangez les fromages et remplissez le centre des bateaux.\n4. Enfournez pour 15-20 min jusqu'à ce que la pâte soit dorée.\n5. Sortez du four, creusez un petit puits dans le fromage et cassez un œuf au centre de chaque bateau.\n6. Remettez au four 2-3 min (le blanc doit être pris, le jaune coulant). Ajoutez une noisette de beurre avant de servir chaud.`
  },
  {
    id: 'r52',
    title: 'Lontong Sayur',
    description: 'Une soupe de légumes indonésienne au lait de coco parfumée, traditionnellement servie avec des gâteaux de riz.',
    country: 'Indonésie',
    calories: 450,
    portions: 4,
    preparationTime: 40,
    isEconomical: true,
    ingredients: [
      { name: 'Lait de coco', quantity: 1, unit: 'L' },
      { name: 'Haricots verts', quantity: 200, unit: 'g' },
      { name: 'Chou blanc émincé', quantity: 200, unit: 'g' },
      { name: 'Curcuma', quantity: 1, unit: 'cuillère à café' },
      { name: 'Gingembre', quantity: 2, unit: 'cm' },
      { name: 'Oeufs durs', quantity: 4, unit: 'pièce' },
    ],
    preparation: `1. Faites chauffer le lait de coco avec le curcuma, le gingembre et du sel.\n2. Ajoutez les légumes (haricots, chou) et portez à frémissement.\n3. Laissez mijoter 20 minutes jusqu'à ce que les légumes soient tendres.\n4. Ajoutez les œufs durs coupés en deux en fin de cuisson.\n5. Servez chaud avec du riz ou des nouilles.`
  },
  {
    id: 'r53',
    title: 'Bobotie Sud-Africain',
    description: 'Un hachis de viande épicé et fruité surmonté d\'un flan crémeux au curcuma.',
    country: 'Afrique du Sud',
    calories: 600,
    portions: 4,
    preparationTime: 50,
    isEconomical: false,
    ingredients: [
      { name: 'Bœuf haché', quantity: 500, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pièce' },
      { name: 'Poudre de curry doux', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Confiture d\'abricots', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Oeufs', quantity: 2, unit: 'pièce' },
      { name: 'Lait', quantity: 250, unit: 'ml' },
    ],
    preparation: `1. Faites revenir l'oignon et le bœuf. Ajoutez le curry et la confiture. Salez et poivrez.\n2. Mettez le mélange dans un plat à four.\n3. Battez les œufs avec le lait et une pincée de curcuma. Versez sur la viande.\n4. Enfournez à 180°C pendant 30 minutes jusqu'à ce que le flan soit pris et doré.\n5. Servez traditionnellement avec du riz au safran et des chutneys.`
  },
  {
    id: 'r54',
    title: 'Adobo de Poulet',
    description: 'Le plat national philippin : du poulet mijoté dans un mélange équilibré de vinaigre, sauce soja et ail.',
    country: 'Philippines',
    calories: 500,
    portions: 4,
    preparationTime: 45,
    isEconomical: true,
    ingredients: [
      { name: 'Cuisses de poulet', quantity: 800, unit: 'g' },
      { name: 'Sauce soja', quantity: 100, unit: 'ml' },
      { name: 'Vinaigre de riz', quantity: 60, unit: 'ml' },
      { name: 'Ail haché', quantity: 1, unit: 'tête entière' },
      { name: 'Feuilles de laurier', quantity: 3, unit: 'pièce' },
      { name: 'Poivre noir en grains', quantity: 1, unit: 'cuillère à café' },
    ],
    preparation: `1. Marinez le poulet dans la sauce soja, le vinaigre et l'ail pendant 30 min.\n2. Mettez le tout dans une casserole avec le laurier et le poivre.\n3. Portez à ébullition, puis baissez le feu et laissez mijoter 30-40 min jusqu'à ce que la sauce soit réduite et sirupeuse.\n4. Si vous préférez, faites griller rapidement le poulet juste avant de servir pour plus de croustillant.\n5. Servez avec beaucoup de riz blanc.`
  },
  {
    id: 'r55',
    title: 'Pupusas El Salvador',
    description: 'Épaisses galettes de maïs fourrées au fromage et aux haricots, servies avec une salade de chou croquante.',
    country: 'Salvador',
    calories: 400,
    portions: 2,
    preparationTime: 30,
    isEconomical: true,
    ingredients: [
      { name: 'Farine de maïs instantanée', quantity: 300, unit: 'g' },
      { name: 'Mozzarella râpée', quantity: 150, unit: 'g' },
      { name: 'Haricots rouges écrasés', quantity: 100, unit: 'g' },
      { name: 'Eau tiède', quantity: 250, unit: 'ml' },
    ],
    preparation: `1. Mélangez la farine et l'eau pour former une pâte souple.\n2. Formez une boule, creusez-la et mettez un peu de fromage et de haricots au centre. Refermez.\n3. Aplatissez délicatement pour former un disque épais.\n4. Faites cuire sur une poêle chaude sans trop de matière grasse 4-5 min de chaque côté.\n5. Servez avec du "Curtido" (salade de chou vinaigrée).`
  },
  {
    id: 'r56',
    title: 'Moussaka Végétarienne au Lentilles',
    description: 'Une version saine et riche en saveurs de la moussaka classique avec une farce aux lentilles corail.',
    country: 'Grèce / Levant',
    calories: 450,
    portions: 4,
    preparationTime: 60,
    isEconomical: true,
    ingredients: [
      { name: 'Aubergine', quantity: 2, unit: 'pièce' },
      { name: 'Lentilles corail', quantity: 200, unit: 'g' },
      { name: 'Sauce tomate', quantity: 400, unit: 'ml' },
      { name: 'Pommes de terre', quantity: 2, unit: 'pièce' },
      { name: 'Yaourt grec', quantity: 200, unit: 'g' },
      { name: 'Oeufs', quantity: 1, unit: 'pièce' },
    ],
    preparation: `1. Coupez aubergines et patates en rondelles et faites-les précuire au four.\n2. Faites mijoter les lentilles dans la sauce tomate avec du cumin.\n3. Alternez les couches de légumes et de lentilles dans un plat.\n4. Battez le yaourt avec l'œuf et versez sur le dessus.\n5. Enfournez 30 min à 190°C jusqu'à ce que le dessus soit doré.`
  },
  {
    id: 'r57',
    title: 'Bulgogi (Bœuf Coréen)',
    description: 'Fines tranches de bœuf marinées et grillées, un équilibre parfait entre sucré, salé et fumé.',
    country: 'Corée du Sud',
    calories: 550,
    portions: 2,
    preparationTime: 20,
    isEconomical: false,
    ingredients: [
      { name: 'Faux-filet de bœuf', quantity: 400, unit: 'g' },
      { name: 'Sauce soja', quantity: 4, unit: 'cuillère à soupe' },
      { name: 'Sucre', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Huile de sésame', quantity: 1, unit: 'cuillère à soupe' },
      { name: 'Ail haché', quantity: 1, unit: 'cuillère à soupe' },
      { name: 'Oignon vert', quantity: 2, unit: 'pièce' },
    ],
    preparation: `1. Coupez le bœuf en tranches très fines (placez-le 30 min au congélateur avant pour faciliter la coupe).\n2. Mélangez tous les ingrédients de la marinade.\n3. Marinez la viande au moins 30 min.\n4. Faites sauter à feu vif dans un wok ou une poêle très chaude.\n5. Servez avec du riz et des feuilles de laitue pour faire des wraps.`
  },
  {
    id: 'r58',
    title: 'Coxinha de Frango',
    description: 'Petites "cuisses" brésiliennes de pâte farcies de poulet haché épicé et de fromage crémeux.',
    country: 'Brésil',
    calories: 350,
    portions: 4,
    preparationTime: 60,
    isEconomical: true,
    ingredients: [
      { name: 'Filet de poulet cuit et émietté', quantity: 300, unit: 'g' },
      { name: 'Farine', quantity: 250, unit: 'g' },
      { name: 'Bouillon de poulet', quantity: 500, unit: 'ml' },
      { name: 'Fromage à la crème', quantity: 100, unit: 'g' },
      { name: 'Chapelure', quantity: 100, unit: 'g' },
    ],
    preparation: `1. Faites bouillir le bouillon, versez la farine d'un coup et mélangez jusqu'à former une boule de pâte. Laissez refroidir.\n2. Mélangez le poulet avec le fromage crémeux.\n3. Prenez un peu de pâte, aplatissez-la, mettez la farce et refermez en forme de goutte d'eau (poire).\n4. Passez dans l'œuf (optionnel) puis la chapelure.\n5. Faites frire jusqu'à ce que ce soit croustillant et doré.`
  },
  {
    id: 'r59',
    title: 'Gado-Gado',
    description: 'Une salade indonésienne tiède de légumes variés, tofu et œufs, nappée d\'une sauce aux cacahuètes divine.',
    country: 'Indonésie',
    calories: 400,
    portions: 2,
    preparationTime: 25,
    isEconomical: true,
    ingredients: [
      { name: 'Pommes de terre cuites', quantity: 2, unit: 'pièce' },
      { name: 'Haricots verts', quantity: 100, unit: 'g' },
      { name: 'Tofu ferme frit', quantity: 100, unit: 'g' },
      { name: 'Oeufs durs', quantity: 2, unit: 'pièce' },
      { name: 'Beurre de cacahuète', quantity: 4, unit: 'cuillère à soupe' },
      { name: 'Lait de coco', quantity: 50, unit: 'ml' },
    ],
    preparation: `1. Blanchissez les légumes séparément. Coupez le tofu en dés.\n2. Préparez la sauce : mélangez beurre de cacahuète, lait de coco, un peu de piment et de jus de lime.\n3. Disposez les légumes, le tofu et les œufs sur une assiette.\n4. Versez généreusement la sauce tiède sur le tout.\n5. Servez avec des crackers de crevettes (Krupuk) si vous en avez.`
  },
  {
    id: 'r60',
    title: 'Bun Cha',
    description: 'Boulettes de porc grillées servies dans un bouillon acidulé avec des nouilles de riz fraîches et des herbes aromatiques.',
    country: 'Vietnam',
    calories: 550,
    portions: 2,
    preparationTime: 35,
    isEconomical: false,
    ingredients: [
      { name: 'Porc haché', quantity: 300, unit: 'g' },
      { name: 'Nouilles de riz fines', quantity: 200, unit: 'g' },
      { name: 'Sauce poisson', quantity: 4, unit: 'cuillère à soupe' },
      { name: 'Sucre', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Vinaigre de riz', quantity: 2, unit: 'cuillère à soupe' },
      { name: 'Herbes fraîches (menthe, coriandre)', quantity: 1, unit: 'bouquet' },
    ],
    preparation: `1. Formez des boulettes de porc assaisonnées et faites-les griller.\n2. Préparez le bouillon (nuoc cham) : mélangez sauce poisson, vinaigre, sucre, eau chaude et piment.\n3. Faites cuire les nouilles de riz.\n4. Servez les boulettes dans le bouillon chaud, avec les nouilles et les herbes à côté pour que chacun fasse son propre bol.\n5. Un délice très frais et parfumé !`
  }
];
